name: Alpha v stocktrack

on:
  push:
    branches: [ main ]

jobs:
  update_prices:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r requirements.txt 
    - name: Run Python script
      run: python alpha_v_stocktrack.py  
